version: "3.9"

services:
  catalogDb:
    image: postgres
    container_name: catalogDb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
  basketDb:
    image: postgres
    container_name: basketDb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: basketDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data
  distributedcache:
    image: redis
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  # catalogapi:
  #   image: catalogapi
  #   build:
  #     context: .
  #     dockerfile: src/Services/Catalog/Catalog.Api/Dockerfile
  #   ports:
  #     - 5119:5119
  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - catalogDb
      - basketDb
volumes:
  postgres_basket:
  postgres_catalog:
